---
## Default Logstash configuration from logstash-docker.
## from https://github.com/elastic/logstash-docker/blob/master/build/logstash/config/logstash-x-pack.yml
#
http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.url: http://192.168.20.104:9200
xpack.monitoring.elasticsearch.username: logstash_system
xpack.monitoring.elasticsearch.password: changeme
#
# unset by default. see:
# https://www.elastic.co/guide/en/logstash/current/ls-security.html#ls-monitoring-user
#
# By default, the logstash_system user does not have a password, it will not be enabled until you set a password.
# Set the password through the change password API, using "Kibana Dev Tools"
# PUT _xpack/security/user/logstash_system/_password
#{
#  "password": "changeme"
#}

